# Generated by Django 4.2.16 on 2025-01-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlubPilkarski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('miasto', models.CharField(max_length=40)),
                ('rok_zalozenia', models.IntegerField()),
                ('liga', models.CharField(choices=[('Ekstraklasa', 'Ekstraklasa'), ('I Liga', 'I Liga'), ('II Liga', 'II Liga'), ('III Liga', 'III Liga'), ('IV Liga', 'IV Liga'), ('Liga Okregowa', 'Liga Okregowa'), ('A Klasa', 'A Klasa'), ('B Klasa', 'B Klasa')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=15)),
                ('data_urodzenia', models.DateField()),
                ('narodowosc', models.CharField(max_length=15)),
                ('pozycja', models.CharField(max_length=15)),
                ('przynaleznosc_klubowa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zawodnicy', to='myapp.klubpilkarski')),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=15)),
                ('trener_klubu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trener', to='myapp.klubpilkarski')),
            ],
        ),
        migrations.CreateModel(
            name='Statystyki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba_meczow', models.IntegerField(default=0)),
                ('mecze_wygrane', models.IntegerField(default=0)),
                ('mecze_zremisowane', models.IntegerField(default=0)),
                ('mecze_przegrane', models.IntegerField(default=0)),
                ('bramki_strzelone', models.IntegerField(default=0)),
                ('bramki_stracone', models.IntegerField(default=0)),
                ('klub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statystyki', to='myapp.klubpilkarski')),
            ],
        ),
        migrations.CreateModel(
            name='Mecz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba_goli_gospodarzy', models.IntegerField()),
                ('liczba_goli_gosci', models.IntegerField()),
                ('data_meczu', models.DateField()),
                ('druzyna_gosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecze_goscie', to='myapp.klubpilkarski')),
                ('druzyna_gospodarzy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mecze_gospodarze', to='myapp.klubpilkarski')),
                ('zawodnik_meczu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.zawodnik')),
            ],
        ),
    ]
